# Generated by Django 5.0.6 on 2024-06-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.product_category')),
            ],
        ),
    ]
