# Generated by Django 5.0.6 on 2024-06-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0002_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='project_images/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.product_category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.sub_category')),
            ],
        ),
    ]
