# Generated by Django 5.0.6 on 2024-06-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0003_chatmessage_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
