# Generated by Django 5.0.6 on 2024-06-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0005_clientreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_details',
            new_name='ProductDetails',
        ),
    ]
