# Generated by Django 5.0.6 on 2024-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0006_rename_product_details_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
