# Generated by Django 5.0.6 on 2024-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0010_rename_name_new_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
