# Generated by Django 5.0.6 on 2024-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0011_alter_contactmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
