# Generated by Django 5.0.6 on 2024-06-17 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0012_alter_contactmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
