# Generated by Django 5.0.6 on 2024-07-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0016_featured_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_details', models.CharField(max_length=20000)),
                ('posted_date', models.DateField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
