# Generated by Django 5.0.6 on 2024-07-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0018_job_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Featured_Product_Details',
            new_name='Featured_Products',
        ),
    ]
