# Generated by Django 5.0.6 on 2024-07-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0019_rename_featured_product_details_featured_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.featured_category'),
        ),
    ]
