# Generated by Django 5.0.6 on 2024-07-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0020_alter_featured_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
