# Generated by Django 5.0.6 on 2024-07-03 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0021_remove_sub_category_category_delete_productdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_model',
            name='job_details',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
