# Generated by Django 5.0.6 on 2024-07-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0023_collectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_collection_type', models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace'), ('anklet', 'Anklet'), ('bangles', 'Bangles'), ('bracelet', 'Bracelet'), ('chain', 'Chain'), ('earrings', 'Earrings'), ('pendants', 'Pendants')], default='ring', max_length=50)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.collectionmodel')),
            ],
        ),
    ]
