# Generated by Django 5.0.6 on 2024-07-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0024_sub_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('SubCollections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.sub_collections')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alapatt.collectionmodel')),
            ],
        ),
    ]
