# Generated by Django 5.0.6 on 2024-07-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alapatt', '0027_rename_subcollections_collectionproducts_sub_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_model',
            name='job_details',
            field=models.TextField(),
        ),
    ]
